micronaut:
  application:
    name: micronautHelloWorld
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    #schema-generate: CREATE_DROP
    dialect: MYSQL
# jpa.default.properties.hibernate.hbm2ddl.auto: validate
jpa:
  default:
    packages-to-scan: 'com.cashstar'
    properties:
      hibernate:
        hbm2ddl:
          auto: none


